### ISSUE TITLE
If we are not available ticket number or id on admin and customer panel showing internal server error instead of page not found

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#487]
**Description**  
If we are not available ticket number showing internal server error instead of page not found

**How to reproduce**  
Step 1: Log in your admin and customer dashboard
Step 2: Now click on the ticket option 
Step 3: Now click on any ticket and open it after changing the URL write any ticket number not available in your admin panel 
Step 4: Same as customer side follow these steps

**Possible Solution**  
If we are not available to ticket number or id on admin and customer panel should be show page not found like this:
![image](https://user-images.githubusercontent.com/63539748/145146067-ff0e71e9-fdf2-4a98-8005-d6179275441d.png)

**Additional context**  
![ticket id not save](https://user-images.githubusercontent.com/63539748/145146470-b8b6ccd8-12ad-470d-bc21-d04b635d39a5.png)

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 

Fixed, Please check

**Comment by Komal-sharma-2712** [comment]
@vipin-shrivastava 
I have checked this issue but still facing the same problem

I have copied and pasted your updated code into the project but still the same issue
and I am also taking a clone of master again and copy-paste the src folder in our project after running this command: 
**php bin/console c:c** showing an error
![500-prob](https://user-images.githubusercontent.com/63539748/146187799-1bb64d25-4c07-4165-9a3c-0422f814e515.png)

**Comment by Komal-sharma-2712** [comment]
@vipin-shrivastava 
I have checked this again now it solved the problem but on the customer, side showing the forbidden page after clicking on the logo

![image](https://user-images.githubusercontent.com/63539748/146330838-724fdc2b-a355-401d-9759-9ef6662407cd.png)

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 

Please test on the office system.

**Comment by Komal-sharma-2712** [comment]
@vipin-shrivastava 
I have tested on the office system

**Comment by PeopleInside** [comment]
For me looks is working.

**Comment by vipin-shrivastava** [comment]
@PeopleInside @Komal-sharma-2712 

Yes, it is working.

**Comment by Komal-sharma-2712** [comment]
@vipin-shrivastava 
I have tested with the new install project of uvdesk with the latest clone from masters:
**core-framework, support-center-bundle, mailbox-component**, and **src -> EventListener** folder update from here: [https://github.com/uvdesk/community-skeleton/blob/master/src/EventListener/ExceptionSubscriber.php](url)

and all have updates in dev mode after changes these files I run this command:
**php bin/console c:c**

After that change in prod mode and again run this command:
**php bin/console c:c**


From the admin side:
https://www.loom.com/share/0860ce77fa464005a7d497e70cbd685a

But first, nothing showed like this if copy-paste URL to another tab but now showing forbidden page instead of the login page of member or customer

From customer side: 
https://www.loom.com/share/5c494cd1a8da48d6bce9866cacece075


**Expected output:** 
This is an old project and here if we are log out customer so after copy-paste should be shown customer login page:
https://www.loom.com/share/2069d78c5ff543d9a7bdf623d91a46bd
