### ISSUE TITLE
In ticket type code field should be shown limit warning message 

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#527]
**Description**  
In ticket type, **code** field should be shown limit warning message: **This field contains a maximum of 191 characters only**

**How to reproduce**  
Step 1: Go to the admin panel and click on the ticket type option
Step 2: Now write more than 191 characters and save so here showing an error.

**Possible Solution**  
If we write more than 191 characters so should be shown a warning message: **This field contains a maximum of 191 characters only**

**Additional context**  
When using more than 191 characters showing an error:
![image](https://user-images.githubusercontent.com/63539748/147242641-3d78cc3f-bae7-45df-b1b9-f5e77b9fbf42.png)

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 

Fixed, Please check

**Comment by Komal-sharma-2712** [comment]
@vipin-shrivastava
I have checked this issue but still facing the same error.
