### ISSUE TITLE
When using prepared responses with more than 100 words in name and description so validation is not working properly

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#528]
**Description**  
When using prepared responses with more than 100 words in **name and description** so validation is not working properly and after save shows an error.

**How to reproduce**  
Step 1: Go to the admin panel and click on prepared responses.
Step 2: Now write more than 100 characters in name and description and save but here showing an error.

**Possible Solution**  
If we more than 100 words should be shown a warning message: **Warning! Please add a valid Name! Length must not be greater than 100** instead of an error.
![image](https://user-images.githubusercontent.com/63539748/147318388-ad91cec5-dc5b-444a-8978-8ac17141f0c5.png)

**Additional context**  
When more than 100 characters and save:
![image](https://user-images.githubusercontent.com/63539748/147318346-5b1aa8d2-6f10-4091-b9bf-25fc329f922f.png)

After save prepared responses showing an error:
![image](https://user-images.githubusercontent.com/63539748/147318312-253580f3-5379-4402-ad57-63339ce1485c.png)

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 

Fixed, Please check

**Comment by Komal-sharma-2712** [comment]
@vipin-shrivastava 
I have checked this issue but still facing the same error.

**Comment by Komal-sharma-2712** [comment]
Now, this issue is resolved now here is an updated commit code in branch 1.1:

https://github.com/uvdesk/automation-bundle/commit/fed4989689b002ebe8e50d953f029ed255d959cd
